# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  messages: 
    basename: messages
  application:
    name: movies-app
server:
  port: 8081
app:
  folder:
    customer: profiles.json
    movie: movies.xml
  fileType:
    json: json
    xml: xml
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.santosh.moviesapp: trace
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql: trace
    
    
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: C:/Projects/logs/application.log

   